title: yoxtellar
description: sound works
url: "https://yoxtellar.github.io"  # ← GitHubのユーザー名に合わせて変更
baseurl: ""  # リポジトリ名がusername.github.ioなら空、それ以外なら "/リポジトリ名"

# Adobe Fonts embed code (typekit)
# adobe_fonts_id: "XXXXXXX"  # ← use.typekit.net のIDを入れる

plugins:
  - jekyll-seo-tag
