title: yoxtellar
description: sound works
url: "https://yamashoyotto.github.io"  # ← GitHubのユーザー名に合わせて変更
baseurl: "/yoxtellar"

# Adobe Fonts embed code (typekit)
# adobe_fonts_id: "XXXXXXX"  # ← use.typekit.net のIDを入れる

plugins:
  - jekyll-seo-tag
